# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h4A-uWYfgegTtUwh3Y5-MkuBIkUvyNy7
"""

import pandas as pd
import numpy as np
from statsmodels.tsa.arima.model import ARIMA
import matplotlib.pyplot as plt
from datetime import timedelta

file_path = 'Amazon_Electronics_Sales_Egypt..xlsx'
df_performance = pd.read_excel(file_path, sheet_name='PERFORMANCE')

df_performance['YearMonth'] = pd.to_datetime(df_performance['YearMonth'])
df_performance = df_performance.sort_values('YearMonth').reset_index(drop=True)

monthly_data = df_performance.groupby('YearMonth').agg({
    'Total_Revenue': 'sum',
    'Profit': 'sum'
}).reset_index()

#Total Revenue
model_revenue = ARIMA(monthly_data['Total_Revenue'], order=(1, 1, 1))
fitted_revenue = model_revenue.fit()
print(fitted_revenue.summary())

#profit
model_profit = ARIMA(monthly_data['Profit'], order=(1, 1, 1))
fitted_profit = model_profit.fit()
print(fitted_profit.summary())

#forecast for 12 months
forecast_steps = 12

forecast_revenue = fitted_revenue.get_forecast(steps=forecast_steps)
forecast_profit = fitted_profit.get_forecast(steps=forecast_steps)

forecast_rev_values = forecast_revenue.predicted_mean
forecast_rev_ci = forecast_revenue.conf_int()
forecast_prof_values = forecast_profit.predicted_mean
forecast_prof_ci = forecast_profit.conf_int()

last_date = monthly_data['YearMonth'].max()
future_dates = pd.date_range(start=last_date + timedelta(days=1),
                             periods=forecast_steps, freq='MS')

#dataframe
forecast_results = pd.DataFrame({
    'YearMonth': future_dates,
    'Forecasted_Revenue': forecast_rev_values.values,
    'Revenue_Lower_CI': forecast_rev_ci.iloc[:, 0].values,
    'Revenue_Upper_CI': forecast_rev_ci.iloc[:, 1].values,
    'Forecasted_Profit': forecast_prof_values.values,
    'Profit_Lower_CI': forecast_prof_ci.iloc[:, 0].values,
    'Profit_Upper_CI': forecast_prof_ci.iloc[:, 1].values,
})

print("\nforecast_results: ")
print(forecast_results.to_string(index=False))

forecast_results.to_csv('forecast_results.csv', index=False)

fig, axes = plt.subplots(2, 1, figsize=(14, 10))


axes[0].plot(monthly_data['YearMonth'], monthly_data['Total_Revenue'],
             'b-', label='Historical Data', linewidth=2)
axes[0].plot(future_dates, forecast_rev_values, 'r-',
             label='Forecasts', linewidth=2)
axes[0].fill_between(future_dates,
                      forecast_rev_ci.iloc[:, 0],
                      forecast_rev_ci.iloc[:, 1],
                      color='red', alpha=0.2, label='95% Confidence Interval')
axes[0].set_title('Revenue Forecasts - Amazon Sales', fontsize=14, fontweight='bold')
axes[0].set_ylabel('Revenue', fontsize=12)
axes[0].legend(loc='best')
axes[0].grid(True, alpha=0.3)


axes[1].plot(monthly_data['YearMonth'], monthly_data['Profit'],
             'g-', label='Historical Data', linewidth=2)
axes[1].plot(future_dates, forecast_prof_values, 'orange',
             label='Forecasts', linewidth=2)
axes[1].fill_between(future_dates,
                      forecast_prof_ci.iloc[:, 0],
                      forecast_prof_ci.iloc[:, 1],
                      color='orange', alpha=0.2, label='95% Confidence Interval')
axes[1].set_title('Profit Forecasts - Amazon Sales', fontsize=14, fontweight='bold')
axes[1].set_ylabel('Profit', fontsize=12)
axes[1].set_xlabel('Date', fontsize=12)
axes[1].legend(loc='best')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('amazon_forecast_visualization.png', dpi=300, bbox_inches='tight')
print("\nChart saved: amazon_forecast_visualization.png")
plt.show()

print("FORECAST STATISTICS:")
print(f"\nRevenue:")
print(f"  Average Forecast: {forecast_rev_values.mean():.2f}")
print(f"  Minimum: {forecast_rev_values.min():.2f}")
print(f"  Maximum: {forecast_rev_values.max():.2f}")
print(f"  Standard Deviation: {forecast_rev_values.std():.2f}")

print(f"\nProfit:")
print(f"  Average Forecast: {forecast_prof_values.mean():.2f}")
print(f"  Minimum: {forecast_prof_values.min():.2f}")
print(f"  Maximum: {forecast_prof_values.max():.2f}")
print(f"  Standard Deviation: {forecast_prof_values.std():.2f}")

print("\nCOMPARISON WITH HISTORICAL DATA:")

hist_avg_rev = monthly_data['Total_Revenue'].mean()
hist_avg_prof = monthly_data['Profit'].mean()

print(f"\nRevenue:")
print(f"  Historical Average: {hist_avg_rev:.2f}")
print(f"  Forecasted Average: {forecast_rev_values.mean():.2f}")
print(f"  Expected Change: {((forecast_rev_values.mean() - hist_avg_rev) / hist_avg_rev * 100):+.2f}%")

print(f"\nProfit:")
print(f"  Historical Average: {hist_avg_prof:.2f}")
print(f"  Forecasted Average: {forecast_prof_values.mean():.2f}")
print(f"  Expected Change: {((forecast_prof_values.mean() - hist_avg_prof) / hist_avg_prof * 100):+.2f}%")